### PR TITLE
feat(failing): show failing test

### PR DESCRIPTION
**Pull request by sibelius**
failing test for #12

image

### CODE REVIEW

**Comment by cdlewis** [comment]
Interesting, do you think this might be related to the typescript parser?

**Comment by sibelius** [comment]
I think so, can we have tests for normal parse and also typescript parser?

**Comment by cdlewis** [comment]
We can! My last commit added typescript testing

**Comment by sibelius** [comment]
Tks great work

I’ve found another issue, it isn’t removing some comments if idx is the first import or the only one

**Comment by sibelius** [comment]
Gonna close this as works well for this case

**Pull request closed without merging**
